/*
 * ioconf.c 
 * Generated by config program
 */

#include <sys/param.h>
#include <sys/device.h>
#include <sys/buf.h>
#include <machine/pte.h>

#define C (caddr_t)
#define D &isa_devtab

/*
 * ISA devices
 */

#include <i386/isa/isa_device.h>
#include <i386/isa/isa.h>
#include <i386/isa/icu.h>

extern struct cfdriver      pccd;
extern struct cfdriver     comcd;
extern struct cfdriver     lptcd;
extern struct cfdriver     wdccd;
extern struct cfdriver      wdcd;
extern struct cfdriver      wdcd;
extern struct cfdriver     fdccd;
extern struct cfdriver      fdcd;
extern struct cfdriver     pcicd;
extern struct cfdriver      edcd;
extern struct cfdriver     npxcd;

struct isa_device isa_devtab[] = {
/*    driver    iobase    irq drq      maddr   msiz unit   flags phys parent */
{ &     pccd,   IO_KBD,  IRQ1, -1, C 0x00000,     0,   0, 0x0000,   0,  NULL },
{ &    comcd,  IO_COM1,  IRQ4, -1, C 0x00000,     0,   0, 0x0000,   0,  NULL },
{ &    lptcd,  IO_LPT1,  IRQ7, -1, C 0x00000,     0,   0, 0x0000,   0,  NULL },
{ &    wdccd,   IO_WD1, IRQ14, -1, C 0x00000,     0,   0, 0x0000,   0,  NULL },
{ &     wdcd,   0x0000,     0, -1, C 0x00000,     0,   0, 0x0000,  -1, D[ 3] },
{ &     wdcd,   0x0000,     0, -1, C 0x00000,     0,   1, 0x0000,  -1, D[ 3] },
{ &    fdccd,   IO_FD1,  IRQ6,  2, C 0x00000,     0,   0, 0x0000,   0,  NULL },
{ &     fdcd,   0x0000,     0, -1, C 0x00000,     0,   0, 0x0000,  -1, D[ 6] },
{ &    pcicd,   0x0000,     0, -1, C 0x00000,     0,   0, 0x0000,   0,  NULL },
{ &     edcd,   0x0320, IRQ10, -1, C 0x00000,     0,   0, 0x0000,   0,  NULL },
{ &    npxcd,   IO_NPX, IRQ13, -1, C 0x00000,     0,   0, 0x0000,   0,  NULL },
0
};

/* pseudo-devices */
extern void loopattach __P((int));
extern void ptyattach __P((int));
extern void slattach __P((int));
extern void speakerattach __P((int));

struct pdevinit pdevinit[] = {
	{ loopattach, 0 },
	{ ptyattach, 32 },
	{ slattach, 1 },
	{ speakerattach, 0 },
	{ 0, 0 }
};
