/*
 * AT/386
 * Macros for interrupt vector routines
 * Generated by config program
 */

#define BUILD_VECTORS \
	BUILD_VECTOR(clk, 0,0,0, _clockmask, _clockintr,1,1,       al);\
	BUILD_VECTOR(ed0, 0,10,1, _ed0mask, _edintr,2,1_AND_2, ah);\


#define	NR_REAL_INT_HANDLERS	2
